# References
- https://www.earthdatascience.org/courses/earth-analytics-python/using-apis-natural-language-processing-twitter/get-and-use-twitter-data-in-python/

- Mapping Disasters with Social Media
 By: Femi Adenugba, Sue Moy, and Teng Mao at General Assembly in DSI-8-Boston
     https://github.com/TengCXXI/Mapping-Disasters-with-Social-Media/blob/master/code/twitter_api_tweet_collection.ipynb

In [104]:
# !pip install tweepy

In [105]:
import tweepy
import pandas as pd
import json

In [106]:
# Load credentials from json file
with open("twitter_credentials.json", "r") as file:
    creds = json.load(file)

In [107]:
consumer_key= creds['CONSUMER_KEY']
consumer_secret= creds['CONSUMER_SECRET']
access_token= creds['ACCESS_TOKEN']
access_token_secret= creds['ACCESS_SECRET']

In [108]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit=True)

In [109]:
search_words = '#DSI9PROJECT5TEST'   #Ability to add Whatever "trending" tags are being used.
date_since = "2016-11-01"
result_type = "mixed"
# since_id = "1154109669021036546"      # enter the id_str from the last ID of the tweets you got from the last loop

In [110]:
tweets = tweepy.Cursor(api.search,
                       q=search_words,
                       #lang="en",                 #In disaster scenarios we wouldn't want to limit searches to one language
                       result_type=result_type,
#                        since_id=since_id         
                      ).items(1000)                #1000 most recent tweets
tweets

In [111]:
tweets_json = [[
                tweet.user.screen_name, 
                tweet.id_str, 
                tweet.created_at, 
                tweet.coordinates, 
                tweet.place,
                tweet.text, 
                tweet.geo 
                ] for tweet in tweets]

In [112]:
tweets_df = pd.DataFrame(tweets_json, columns = [ 
                                                'screen_name', 
                                                'id_str', 
                                                'created_at',
                                                'coordinates',
                                                'place', 
                                                'text',
                                                'geo_location'
                                               ])

In [113]:
tweets_df

,screen_name,id_str,created_at,coordinates,place,text,geo_location
0,DisasterDSI9,1192515038386556928,2019-11-07 18:51:55,None,None,"rain, flood, broken glass, where are the polic...",None
1,DisasterDSI9,1192514890013061120,2019-11-07 18:51:20,None,None,this is not relevant #DSI9PROJECT5TEST,None
2,DisasterDSI9,1192190403027574784,2019-11-06 21:21:56,None,None,Okay now it’s beer o’clock #DSI9PROJECT5TEST,None
3,DisasterDSI9,1192190000718372864,2019-11-06 21:20:20,None,None,its beer o'clock #DSI9PROJECT5TEST,None
4,DisasterDSI9,1192189060334391298,2019-11-06 21:16:36,None,None,Now you know where im dying #DSI9PROJECT5TEST,None
5,DisasterDSI9,1192179250956251141,2019-11-06 20:37:37,None,None,FLooding dsdas wtf my lkjd cribbo im gonna die...,None
6,DisasterDSI9,1192178562687799298,2019-11-06 20:34:53,None,None,Ayuda a que mi casa se inunde #DSI9PROJECT5TEST,None
7,DisasterDSI9,1192176789424136192,2019-11-06 20:27:50,None,None,"im dying, my house has been blown away #DSI9PR...",None
8,DisasterDSI9,1192176322547716098,2019-11-06 20:25:59,None,None,#DSI9PROJECT5TEST https://t.co/0XdPt7FUHM,None
9,DisasterDSI9,1192133704526835714,2019-11-06 17:36:38,None,None,I hope this shitty storm doesn't cancel my pic...,None
10,DisasterDSI9,1192130225523642368,2019-11-06 17:22:49,None,None,Damn my street is flooded as a bitch #DSI9PROJ...,None

In [114]:
tweets_df["text_count"] = [len(tweets_df['text'][s].split()) for s in range(len(tweets_df['text']))]

In [115]:

tweets_df.to_csv('tweets_demo.csv', index=False)

In [116]:
pd.read_csv('tweets_demo.csv')

,screen_name,id_str,created_at,coordinates,place,text,geo_location,text_count
0,DisasterDSI9,1192515038386556928,2019-11-07 18:51:55,NaN,NaN,"rain, flood, broken glass, where are the polic...",NaN,9
1,DisasterDSI9,1192514890013061120,2019-11-07 18:51:20,NaN,NaN,this is not relevant #DSI9PROJECT5TEST,NaN,5
2,DisasterDSI9,1192190403027574784,2019-11-06 21:21:56,NaN,NaN,Okay now it’s beer o’clock #DSI9PROJECT5TEST,NaN,6
3,DisasterDSI9,1192190000718372864,2019-11-06 21:20:20,NaN,NaN,its beer o'clock #DSI9PROJECT5TEST,NaN,4
4,DisasterDSI9,1192189060334391298,2019-11-06 21:16:36,NaN,NaN,Now you know where im dying #DSI9PROJECT5TEST,NaN,7
5,DisasterDSI9,1192179250956251141,2019-11-06 20:37:37,NaN,NaN,FLooding dsdas wtf my lkjd cribbo im gonna die...,NaN,10
6,DisasterDSI9,1192178562687799298,2019-11-06 20:34:53,NaN,NaN,Ayuda a que mi casa se inunde #DSI9PROJECT5TEST,NaN,8
7,DisasterDSI9,1192176789424136192,2019-11-06 20:27:50,NaN,NaN,"im dying, my house has been blown away #DSI9PR...",NaN,9
8,DisasterDSI9,1192176322547716098,2019-11-06 20:25:59,NaN,NaN,#DSI9PROJECT5TEST https://t.co/0XdPt7FUHM,NaN,2
9,DisasterDSI9,1192133704526835714,2019-11-06 17:36:38,NaN,NaN,I hope this shitty storm doesn't cancel my pic...,NaN,10
10,DisasterDSI9,1192130225523642368,2019-11-06 17:22:49,NaN,NaN,Damn my street is flooded as a bitch #DSI9PROJ...,NaN,9